window.OverworldMaps.S14 = {
        id: "S14",
        lowerSrc: "images/maps/S14Lower.png",
        upperSrc: "images/maps/KitchenUpper.png",
        gameObjects: {
            placeholder: new Person({
               src: "images/maps/KitchenUpper.png"
            }),
            hero: new Person({
                isPlayerControlled: true,
                x: utils.withGrid(14),
                y: utils.withGrid(11),
                useShadow: true,
            }),
        },
        cutsceneSpaces: {
                [utils.asGridCoord(14, 11)]: [
                {
                    events: [
                        {
                            type: "changeMap",
                            map: "KorytarzPrawy",
                            x: utils.withGrid(15),
                            y: utils.withGrid(8),
                            direction: "down"
                        },
                    ]
                }
            ],
        },
        walls: {
            [utils.asGridCoord(14, 12)]: true,
            [utils.asGridCoord(13, 11)]: true,
            [utils.asGridCoord(15, 11)]: true,
            [utils.asGridCoord(15, 8)]: true,
            [utils.asGridCoord(15, 6)]: true,
            [utils.asGridCoord(15, 7)]: true,
            [utils.asGridCoord(15, 3)]: true,
            [utils.asGridCoord(15, 4)]: true,
            [utils.asGridCoord(15, 9)]: true,
            [utils.asGridCoord(15, 10)]: true,
            [utils.asGridCoord(16, 5)]: true,
            [utils.asGridCoord(14, 4)]: true,
            [utils.asGridCoord(10, 4)]: true,
            [utils.asGridCoord(13, 4)]: true,
            [utils.asGridCoord(12, 4)]: true,
            [utils.asGridCoord(11, 4)]: true,
            [utils.asGridCoord(9, 4)]: true,
            [utils.asGridCoord(8, 4)]: true,
            [utils.asGridCoord(7, 4)]: true,
            [utils.asGridCoord(6, 4)]: true,
            [utils.asGridCoord(6, 3)]: true,
            [utils.asGridCoord(5, 2)]: true,
            [utils.asGridCoord(4, 3)]: true,
            [utils.asGridCoord(3, 3)]: true,
            [utils.asGridCoord(2, 3)]: true,
            [utils.asGridCoord(1, 4)]: true,
            [utils.asGridCoord(1, 5)]: true,
            [utils.asGridCoord(1, 6)]: true,
            [utils.asGridCoord(1, 7)]: true,
            [utils.asGridCoord(1, 8)]: true,
            [utils.asGridCoord(1, 9)]: true,
            [utils.asGridCoord(2, 10)]: true,
            [utils.asGridCoord(3, 10)]: true,
            [utils.asGridCoord(4, 10)]: true,
            [utils.asGridCoord(5, 9)]: true,
            [utils.asGridCoord(6, 9)]: true,
            [utils.asGridCoord(7, 9)]: true,
            [utils.asGridCoord(8, 9)]: true,
            [utils.asGridCoord(9, 9)]: true,
            [utils.asGridCoord(10, 9)]: true,
            [utils.asGridCoord(11, 9)]: true,
            [utils.asGridCoord(12, 9)]: true,
            [utils.asGridCoord(12, 10)]: true,
            [utils.asGridCoord(3, 6)]: true,
            [utils.asGridCoord(4, 6)]: true,
            [utils.asGridCoord(5, 6)]: true,
            [utils.asGridCoord(6, 6)]: true,
            [utils.asGridCoord(7, 6)]: true,
            [utils.asGridCoord(8, 6)]: true,
            [utils.asGridCoord(9, 6)]: true,
            [utils.asGridCoord(10, 6)]: true,
            [utils.asGridCoord(11, 6)]: true,
            [utils.asGridCoord(12, 6)]: true,
            [utils.asGridCoord(3, 7)]: true,
            [utils.asGridCoord(4, 7)]: true,
            [utils.asGridCoord(5, 7)]: true,
            [utils.asGridCoord(6, 7)]: true,
            [utils.asGridCoord(7, 7)]: true,
            [utils.asGridCoord(8, 7)]: true,
            [utils.asGridCoord(9, 7)]: true,
            [utils.asGridCoord(10, 7)]: true,
            [utils.asGridCoord(11, 7)]: true,
            [utils.asGridCoord(12, 7)]: true,
        },
    };